### ISSUE TITLE
MQTT_CLIENT_ID is not working with broker

### ISSUE THREAD

**Issue by klinwer** [stlehmann/Flask-MQTT#134]
The MQTT_CLIENT_ID is shown only in the local log file but not used to estabish a connection with mosquitto broker.

mosquitto broker log file:
New client connected from 192.168.178.63:59453 as auto-9C0153A2-9AB7-2D48-94C8-D229D9AA760D (p2, c1, k5, u'WebLamp').

Config mqtt:
app.config["MQTT_CLIENT_ID"] = "WebLamp"
app.config["MQTT_USERNAME"] = global_data["user"]
app.config["MQTT_PASSWORD"] = global_data["password"]
app.config["MQTT_BROKER_URL"] = global_data["broker_address"]
app.config["MQTT_BROKER_PORT"] = global_data["port"]
app.config["MQTT_REFRESH_TIME"] = 1.0  # refresh time in seconds
app.config["MQTT_KEEPALIVE"] = 5
app.config["MQTT_TLS_ENABLED"] = False
app.config["MQTT_CLEAN_SESSION"] = False

**Comment by xiamingtao** [comment]
yes,So did I

**Comment by klinwer** [comment]
Are you able to change it? Other mqtt clients offer this option.

**Comment by ziXet** [comment]
Seems that it's fixed in this PR: https://github.com/stlehmann/Flask-MQTT/pull/77
But they did not release a new version since then!

**Comment by klinwer** [comment]
Thanks for the update.

**Comment by Sohaib90** [comment]
Apologies for the late reply. I have been a little inactive lately on this repo. The new release should fix this problem now. Newer releases will follow but I hope this works now
Link : https://github.com/stlehmann/Flask-MQTT/releases/tag/1.1.2

**Comment by klinwer** [comment]
Hello, 

 

thanks for your feedback.

 

I did already a test with it. It is working as expected. 😊

 

Is it ok that the package still shows version 1.1.1?

 

Regards,

Werner

 

 

Von: Muhammad Sohaib Arshid ***@***.***> 
Gesendet: Donnerstag, 4. Mai 2023 14:12
An: stlehmann/Flask-MQTT ***@***.***>
Cc: klinwer ***@***.***>; Author ***@***.***>
Betreff: Re: [stlehmann/Flask-MQTT] MQTT_CLIENT_ID is not working with broker (Issue #134)

 

Closed #134 <https://github.com/stlehmann/Flask-MQTT/issues/134>  as completed.

**Comment by Sohaib90** [comment]
Hey 

I am working on introducing a github action for the release on pypi as well. Until then it will remain the same
