### ISSUE TITLE
Connect to multiple MQTT Servers

### ISSUE THREAD

**Issue by MattiaudaNicolasCN** [stlehmann/Flask-MQTT#143]
Hi guys,

I would like to ask you when will be available the possibility of connect to multiple MQTT Servers because in the Github README I have seen it but in the release version i'm not able to do it yet. Or How could I use it?

Thank you for your time!

**Comment by Sohaib90** [comment]
Have you tried using the latest release (1.1.2) from the repository?

https://github.com/stlehmann/Flask-MQTT/tree/1.1.2

**Comment by MattiaudaNicolasCN** [comment]
Yes but there is no parameter called `config_prefix` when initializing `Mqtt() `, so I couldn'use it with multiple MQTT Servers

**Comment by Sohaib90** [comment]
Oh yes I see that the latest release does not include the functionality of connecting to multiple MQTT servers. I will rectify that and make a new release soon :) 

Thank you for pointing it out

**Comment by MattiaudaNicolasCN** [comment]
Ok perfect thank you, I'll wait for the new release! 😄

**Comment by MattiaudaNicolasCN** [comment]
Any update?

**Comment by Sohaib90** [comment]
Apologies for the delay. I was stuck with some work and havent been active lately. I will do it soon :)

**Comment by Sohaib90** [comment]
@MattiaudaNicolasCN 

I have released a new version `1.2.0` 
Check it out and see if everything is up to date and working. Otherwise, create a pull request and I will review it :)
