### ISSUE TITLE
paho-mqtt 2.0.0 breaks flask-mqtt

### ISSUE THREAD

**Issue by samjt** [stlehmann/Flask-MQTT#164]
paho-mqtt 2.0.0 requires an argument in it's Client constructor that isn't present in the flask-mqtt wrapper.

This PR fixes the issue:
https://github.com/stlehmann/Flask-MQTT/pull/163

**Comment by tonsmets** [comment]
Please merge this! @stlehmann

**Comment by stlehmann** [comment]
@tonsmets I've not been maintaining this repository actively for a while now. As this project was developed with paho-mqtt < 2 I will pin the version requirements to use paho-mqtt < 2 to clarify things and prevent errors on installation.
