### ISSUE TITLE
on_connect call back

### ISSUE THREAD

**Issue by essramos** [stlehmann/Flask-MQTT#18]
Hello, 

Is there any way I could use an on_connect callback? Because I want to be able to subscribe to topics once I am connected to the broker and not subscribe thru the frontend like on your example. 

Thanks.

**Comment by stlehmann** [comment]
Hi,
there is no on_connect callback at the moment.

**Comment by essramos** [comment]
Is there any recommendation on how to monitor the on_connect using this library? Or how to subscribe to a topic once connected to the broker without actions from the front end?

**Comment by stlehmann** [comment]
For monitoring the on_connect signal you need to write your own callback function and add it to the client

    mqtt.client.on_connect = handle_on_connect

    def handle_on_connect(client, userdata, flags, rc):
        # call the handle_connect method of mqtt at the end
        mqtt._handle_connect(client, userdata, flags, rc)

Could you describe your scenario a bit. I might want to add an ‚is_connected‘ callback to the Mqtt class.

**Comment by essramos** [comment]
From your example on the documentation, subscribing to a topic is triggered when you click on the front end and socketio handles that correct? I want to be able to subscribe to a topic the moment I am connected to my broker. Like you said an ` is_connected ` callback to the Mqtt class. Based on your example from above, it seems like there is an on_connect library but is for internal use only. 
 
e.g
```
@mqtt.on_connect()
def handle_on_connect():
    mqtt.subscribe('/topic')
```

**Comment by stlehmann** [comment]
I added an on_connect and also an on_disconnect callback to the API. Please have a look at it.
