### ISSUE TITLE
subscribe qos not apply 

### ISSUE THREAD

**Issue by AhnSeongHyun** [stlehmann/Flask-MQTT#19]
```python 

import json
from flask import Flask
from flask_mqtt import Mqtt

app = Flask(__name__)
app.config['MQTT_BROKER_URL'] = 'localhost'
app.config['MQTT_BROKER_PORT'] = 1993
app.config['MQTT_KEEPALIVE'] = 30

mqtt = Mqtt(app)
mqtt.subscribe(topic="TEST", qos=2)

app.run()
```

subscribe qos set 2 but only 0. 

I use [emqttd](https://github.com/emqtt/emqttd)
 
![test](https://user-images.githubusercontent.com/1414228/35316485-2e2219fa-0115-11e8-9aee-a8333ad143b6.png)

Topic TEST is paho mqtt and Topic TEST_FLAK_MQTT is flask-mqtt. 

Do not set subscribe qos:2

**Comment by stlehmann** [comment]
That is strange. The subscribe function passes the parameters directly to paho. In your snippet I don't see the topic `TEST_FLASK_MQTT`. For `TEST` it seems to work.

**Comment by AhnSeongHyun** [comment]
my codes are blow:

```python 
import json
from flask import Flask
from flask_mqtt import Mqtt
app = Flask(__name__)
app.config['MQTT_BROKER_URL'] = 'localhost'
app.config['MQTT_BROKER_PORT'] = 1993
app.config['MQTT_KEEPALIVE'] = 30
app.config['MQTT_LAST_WILL_QOS'] = 2
mqtt = Mqtt(app)
mqtt.subscribe(topic="TEST_FLAK_MQTT", qos=2)
app.run()
```

```python 
import paho.mqtt.client as mqtt
mqttc = mqtt.Client()
mqttc.connect("localhost", port=1993, keepalive=60)  
mqttc.subscribe("TEST", 2)
mqttc.loop_forever()
```

**Comment by AhnSeongHyun** [comment]
```
mqtt.subscribe(("TEST_FLAK_MQTT",2)) # tuple 
```
set QOS : 2

```
mqtt.subscribe(topic="TEST_FLAK_MQTTT", qos=2)
```
Not set QOS : 2

**Comment by stlehmann** [comment]
That is strange. I will give it a close look asap.

**Comment by stlehmann** [comment]
The subscription method passes the qos correctly to pahos subscribe function. So this must be an issue between paho and emqttd.

**Comment by stlehmann** [comment]
You have to wait with the subscription until the connection has been established. Use the `on_connect` decorator for this. In your example this would look like this:

    import json
    from flask import Flask
    from flask_mqtt import Mqtt

    app = Flask(__name__)
    app.config['MQTT_BROKER_URL'] = 'localhost'
    app.config['MQTT_KEEPALIVE'] = 30
    app.config['MQTT_LAST_WILL_QOS'] = 2
    
    mqtt = Mqtt(app)

    @mqtt.on_connect()
    def connected(*args, **kwargs):
        mqtt.subscribe("TEST_FLASK_MQTT", 2)

    app.run()
