### ISSUE TITLE
The Flask MQTT Client is recieving the message twice

### ISSUE THREAD

**Issue by mntolia** [stlehmann/Flask-MQTT#24]
Hi,
I have a paho-mqtt client on my PC. When I send a single message to the topic on the broker the message is being received twice by the MQTT client on flask. 

I connected another PC client to the broker and subscribed to the topic and saw that the message is getting received only once. Only on the flask client its getting recieved twice. 

I have an @mqtt.on_connect function that subscribes to only that 1 topic after connection and a single @mqtt.on_message function to handle the messages. Any idea why this issue occurs?

Even the logger shows the same message twice.

**Comment by AhnSeongHyun** [comment]
How to run flask app.py? using Apache mod-wsgi? gunicorn?

**Comment by mntolia** [comment]
I am running it directly on EC2 at the moment. I haven't added a WSGI yet. I am also running it on my PC and encountering the same issue.

**Comment by mntolia** [comment]
I also noticed in the log there are 2 clients being created although there is only 1 client object:
```
16 Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k20) client_id=b''
16 Received CONNACK (0, 0)
16 Sending SUBSCRIBE (d0) [(b'TEST', 0)]
16 Sending SUBSCRIBE (d0) [(b'death', 0)]
16 Received SUBACK
16 Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k20) client_id=b''
16 Received SUBACK
16 Received CONNACK (0, 0)
16 Sending SUBSCRIBE (d0) [(b'TEST', 0)]
16 Sending SUBSCRIBE (d0) [(b'death', 0)]
16 Received SUBACK
16 Received SUBACK
```

**Comment by AhnSeongHyun** [comment]
I think I need to look at the client's code.

**Comment by mntolia** [comment]
I have only included the MQTT relevant code:
views.py:
`import os
from flask import Flask, render_template, redirect, flash, request, url_for
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from flask_bcrypt import Bcrypt
from flask_debugtoolbar import DebugToolbarExtension
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.exc import IntegrityError
from flask_bootstrap import Bootstrap
from datetime import timedelta, datetime
from time import time
from flask_mail import Message, Mail
from flask_mqtt import Mqtt

##############
### config ###
##############

app = Flask(__name__)
app.config.from_object('config')
db = SQLAlchemy(app)
mqtt = Mqtt(app)

@mqtt.on_connect()
def handle_connect(client, userdata, flags, rc):
    mqtt.subscribe("TEST")
    mqtt.subscribe("death")

@mqtt.on_message()
def handle_message(client, userdata, message):
    if message.topic == "TEST":
#

@mqtt.on_disconnect()
def handle_disconnect(client, userdata, rc):
    print("Disconnected from broker")

@mqtt.on_log()
def handle_logging(client, userdata, level, buf):
    print(level, buf)
`
config file:
###MQTT CONFIG

```
MQTT_BROKER_URL = "********"
MQTT_BROKER_PORT = *****
MQTT_KEEPALIVE = 20
MQTT_TLS_ENABLED = False
```

**Comment by mntolia** [comment]
I am circumventing this issue temporarily by creating a client id. That way the first client gets disconnected once the second client connects to it.

**Comment by AhnSeongHyun** [comment]
I test based on your code and use emqtt for mqtt broker server. 
The message is being printed only once.

server code below:

```python 
import os
from flask import Flask, render_template, redirect, flash, request, url_for
from datetime import timedelta, datetime
from time import time
from flask_mqtt import Mqtt
 

app = Flask(__name__)
app.config['MQTT_BROKER_URL'] = "127.0.0.1"
app.config['MQTT_BROKER_PORT'] = 1883
app.config['MQTT_KEEPALIVE'] =20

mqtt = Mqtt(app)

@mqtt.on_connect()
def handle_connect(client, userdata, flags, rc):
    print('on_connect client : {} userdata :{} flags :{} rc:{}'.format(client, userdata, flags, rc))
    mqtt.subscribe("TEST")
    mqtt.subscribe("death")

@mqtt.on_subscribe()
def handle_subscribe(client, userdata, mid, granted_qos):
    print('on_subscribe client : {} userdata :{} mid :{} granted_qos:{}'.format(client, userdata, mid, granted_qos))


@mqtt.on_message()
def handle_message(client, userdata, message):
    print('on_message client : {} userdata :{} message.topic :{} message.payload :{}'.format(
    	client, userdata, message.topic, message.payload.decode()))

@mqtt.on_disconnect()
def handle_disconnect(client, userdata, rc):
    print('on_disconnect client : {} userdata :{} rc :{}'.format(client, userdata, rc))
    

@mqtt.on_log()
def handle_logging(client, userdata, level, buf):
    print(level, buf)

app.run(port=9090)
```

client code using paho client library below:

```python
import paho.mqtt.publish as publish
import time

if __name__ == '__main__': 
    while(True):
        msg = input("enter msg:").strip()
        result = publish.single("TEST", msg, hostname="127.0.0.1", port=1883) 
```

After `python3 app.py` , mqtt client in server connect to broker and then subscribe `TEST` and `death`. 

```
16 Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k20) client_id=b''
16 Received CONNACK (0, 0)
on_connect client : <paho.mqtt.client.Client object at 0x10cb33a90> userdata :None flags :{'session present': 0} rc:0
16 Sending SUBSCRIBE (d0) [(b'TEST', 0)]
16 Sending SUBSCRIBE (d0) [(b'death', 0)]
16 Received SUBACK
on_subscribe client : <paho.mqtt.client.Client object at 0x10cb33a90> userdata :None mid :1 granted_qos:(0,)
16 Received SUBACK
on_subscribe client : <paho.mqtt.client.Client object at 0x10cb33a90> userdata :None mid :2 granted_qos:(0,)
16 Sending PINGREQ
16 Received PINGRESP
```

Run `python3 pub.py` and send message to server. 

client log below:
```
$> python3 pub.py
enter msg:HELLO WORLD
enter msg:JUST TEST
```

server log below:
```
on_message client : <paho.mqtt.client.Client object at 0x10ca23a58> userdata :None message.topic :TEST message.payload :HELLO WORLD
16 Received PUBLISH (d0, q0, r0, m0), 'TEST', ...  (9 bytes)
on_message client : <paho.mqtt.client.Client object at 0x10ca23a58> userdata :None message.topic :TEST message.payload :JUST TEST
```

**Comment by mntolia** [comment]
Thank you.

There is definitely something wrong with my code but I am unable to figure out what it is. This is the file run.py where I run my app:

```
from views import app
import os

port	=	int(os.environ.get('PORT',	5000))
app.run(host = '0.0.0.0', port = port)
```
Its creating 2 clients when I connect to local broker also. 

Also when I make some modification in a file and the app restarts then it creates only 1 client. Only when I first run the app it creates 2 clients.

**Comment by stlehmann** [comment]
If you have debugging enabled (e.g. via FLASK_DEBUG=True) Flask will create 2 instances. If you don't want this behaviour just turn debugging off by setting FLASK_DEBUG to False. Have a look here: http://flask.pocoo.org/docs/0.12/quickstart/#debug-mode

**Comment by mntolia** [comment]
That was the issue. Thanks a lot!

**Comment by AbdallahJarwan** [comment]
> If you have debugging enabled (e.g. via FLASK_DEBUG=True) Flask will create 2 instances. If you don't want this behaviour just turn debugging off by setting FLASK_DEBUG to False. Have a look here: http://flask.pocoo.org/docs/0.12/quickstart/#debug-mode

That was also my case!

**Comment by ohk2kt3t4** [comment]
Perhaps the example code in the README should be amended to turn them off:
`if __name__ == '__main__':
    socketio.run(app, host='0.0.0.0', port=5000, use_reloader=True, debug=True)`

**Comment by richard-linux** [comment]
I was have the same issue, so I did a little digging...
I am using VS Code, and I found two places where a debug flag can be set.

1. In the "if __name__ == '__main__':" block at bottom of app.py (debug=True)
2. In a launch configuration in launch.json ("FLASK_DEBUG": "1")

Since I am using the Run menu in VS Code, I deleted the "if __name__ == '__main__':" block at bottom of app.py, and everything seems to launch and run just fine. That way, debug control is isolated to launch.json.

**Comment by gastmaier** [comment]
I solved in debugging mode with 
```
```

**Comment by gastmaier** [comment]
I have solved in debug mode with:
```
# Run only in main instance
if os.environ.get("WERKZEUG_RUN_MAIN") == "true":
```
Which is okay since I barely modify the MQTT related code.

However, with Apache2 mod_wsgi Daemon Mode this rule won't work, and I get two instances running... Any ideas?
Of course, I could reload Apache2 every time, but it's a boring solution.
