### ISSUE TITLE
Repeated retained message

### ISSUE THREAD

**Issue by Stormhand** [stlehmann/Flask-MQTT#28]
Hello,
im relatively new to flask. I need to log all subscribed topics to database using the existing flask model. Here is my mqtt part:
```
from app import mqtt, create_app, db
from app.models import Logs

ext = create_app()

@mqtt.on_connect()
def handle_connect(client, userdata, flags, rc):
    mqtt.subscribe('home/+/resp')
    mqtt.subscribe('home/+/cmd')
    
@mqtt.on_message()
def handle_mqtt_message(client, userdata, message):  
    topic=message.topic.split('/')
    payload=message.payload.decode()
    d = Logs(topic=topic[2], location=topic[1], body=payload)
    with ext.app_context():
        ext.logger.warn(message.topic)
        db.session.add(d)
        db.session.commit()
```

I register flask-mqtt in flask using the factory method:
```
mqtt.init_app(app)
mqtt.subscribe('home/+/resp')
mqtt.subscribe('home/+/cmd')
```

everything is ok except that when a retained message is published in some of the topics **handle_mqtt_message** seems to be executed many times which floods the database with the same message several times per second, where in the log its once per second:
> 2018-05-31 17:30:08,045 WARNING: home/home/cmd
> 2018-05-31 17:30:09,665 WARNING: home/home/cmd
> 2018-05-31 17:30:10,835 WARNING: home/home/cmd
> 2018-05-31 17:30:11,902 WARNING: home/home/cmd
> 2018-05-31 17:30:12,973 WARNING: home/home/cmd

**Comment by mntolia** [comment]
Is Flask in DEBUG mode?

**Comment by Stormhand** [comment]
No, im using gunicorn.

**Comment by stlehmann** [comment]
@Stormhand Did you set the qos of the message to 1? This would explain the multiple messages. If so try setting it to qos=2 and see if it works.

**Comment by Stormhand** [comment]
I fixed it by moving to the end of app/__init__.py the import:

> from app.services import mqtt as mqtt_srv

then init the mqtt in app/services.py:
```
from app import mqtt, create_app, db
from app.models import Logs

ext = create_app()
mqtt.init_app(ext)
...
```
So it seems the problem is flask related than flask-mqtt

**Comment by Stormhand** [comment]
Unfortunately the problem isn't solved yet. The repeat call occurs randomly but i can't catch it yet.
Replacing flask-mqtt with paho directly in the file with loop_forever() doesn't help. 
Using paho as standalone daemon doesn't have any problems.
Qos 1/2 in subscribe does not have any effect. 
It might be connected to the creating of context. Could you provide some real example using the addon with app context?

**Comment by stlehmann** [comment]
I can' t imagine why this is happening. The on_connect decorator is just a callback passed to pahos on_connect event. Could you try to serve with the build-in flask server via flask run and see if this makes a difference.

**Comment by stlehmann** [comment]
@Stormhand I could reproduce your issue of repeated "connected" messages only by supplying wrong user credentials. This way the  client could not connect to the broker and repeatedly tried to reconnect. Could this be your issue?

**Comment by Stormhand** [comment]
Sorry, im away from my pc to make so tests but my mosquitto broker doesn't need credentials. Two things are on my mind but ill test tonight:
1. Client id which is already used
2. The call to create_app which is already called once by gunicorn to start flask so init(app) is called twice.

**Comment by Stormhand** [comment]
Thats really weird. Here is the broker's log:
```
1528095584: New connection from ::1 on port 1883.
1528095584: New connection from ::1 on port 1883.
1528095585: New connection from ::1 on port 1883.
1528095585: New connection from ::1 on port 1883.
1528095585: Socket error on client <unknown>, disconnecting.
1528095585: Socket error on client <unknown>, disconnecting.
1528095588: New client connected from ::1 as ota_server (c1, k60).
1528095589: New connection from ::1 on port 1883.
1528095589: Client ota_server already connected, closing old connection.
1528095589: Client ota_server disconnected.
```
Then the last four lines are repeated. It doesnt matter if im using flask in debug or gunicorn.

here is my app/__init__.py
```
from flask_mqtt import Mqtt
from config import Config

mqtt = Mqtt()

    
def create_app(config_class=Config, static_url_path='/static'):
    app = Flask(__name__)
    app.config.from_object(config_class)
    
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)
    
    from app.api import bp as api_bp
    app.register_blueprint(api_bp, url_prefix='/api')
    from app.services import mqtt as mqtt_srv
    mqtt.init_app(app)
        
    return app
```

**Comment by stlehmann** [comment]
Using Flask-MQTT within a factory function should be fine. I use it for my applications pretty much as default.
Just an idea: Are you using gevent or eventlet? If so you might need to monkey-patch. 

I don't know what kind of example you would like to see on app context. Could you please clarify it a bit more (maybe example).

**Comment by Stormhand** [comment]
I tried gevent, eventlet and default.

> I don't know what kind of example you would like to see on app context. Could you please clarify it a bit more (maybe example).

Example where the callbacks are able to use the app context. If i dont use create_app() everything is fine.

**Comment by stlehmann** [comment]
Of course, if you don' t use create_app() Flask and the MQTT plugin will not get initialized and nothing happens at all. Sorry, I don't get your point, mate.

**Comment by Stormhand** [comment]
Sorry, this is my first flask app and am still trying to figure out how to arrange my application. Everything else works.
I have a main server.py script which starts my flask app using create_app(). Then my mqtt service calls it again to take the context. So all the init_app()'s have been called two times.

**Comment by stlehmann** [comment]
Flask-MQTT is designed to integrate a MQTT client in Flask and provides several decorators to allow easy handling of incoming messages. You don't need to setup another mqtt client service for this. You can handle it all from within your Flask app. 

If you don't mind just send me the code via mail. Then I can take a look at it.

**Comment by Stormhand** [comment]
I've sent you the code. I guess there is something wrong with my flask structure at all :)

Thanks again.

**Comment by stlehmann** [comment]
Thanks, I' ve got it. There is just one create_app() function too much in your app.services.mqtt module. I've sent you answer by mail as well.

**Comment by Stormhand** [comment]
Thanks, Stefan. 
Closing the issue as its not related to this addon.
