### ISSUE TITLE
Mqtt Instance runs twice on application run

### ISSUE THREAD

**Issue by Rory-Wade** [stlehmann/Flask-MQTT#31]
First off, great implementation of the paho mqtt library, it has saved me a lot of time implementing it into the flask ecosystem. However, an issue with the library that is not directly linked to its functionality is that when the flask server is running with the example code snippet provided, the MQTT code seems to run twice.

 `socketio.run(app, host='0.0.0.0', port=5000, use_reloader=True, debug=True)` 

This is only the case when the application has the perimeters `use_reloader=True, debug=True`. Maybe for future users of the library a small note could be made to the ReadMe file about this characteristic of Flask in debug mode. For Flask newbies like me.    

[Flask functionality with these settings](https://stackoverflow.com/questions/28585033/why-does-a-flask-app-create-two-process?lq=1)

**Comment by stlehmann** [comment]
Thanks for the feedback. I will see to add some hint for the user in the documentation addressing this issue.
