### ISSUE TITLE
Option to set mqtt protocol in client

### ISSUE THREAD

**Issue by niloysh** [stlehmann/Flask-MQTT#32]
According to the [paho docs](https://pypi.org/project/paho-mqtt/#client), the mqtt protocol i.e. MQTTv311 or MQTTv31 can be passed. 
By default, MQTTv311 is passed, which seems to be causing connection issues with mosquitto broker. Refer to [this stackoverflow post](https://stackoverflow.com/questions/38017111/pahomqtt-client-cant-connect). 
I was facing the same problem. Setting MQTTv31 fixed the issue.
However, since there is no option to pass the protocol in flask_mqtt I reverted to normal paho.mqtt
Thus, I think optional argument to pass mqtt protocol to flask_mqtt will be beneficial.
For reference, the optional argument needs to be passed in flask_mqtt/__init\__.py line 75-77.

**Comment by stlehmann** [comment]
Thanks for the feedback. I will see to this soon.
