### ISSUE TITLE
Use connect_async instead of connect

### ISSUE THREAD

**Issue by j123b567** [stlehmann/Flask-MQTT#34]
Web application can't be started if MQTT broker is not running because of an exception during connection. Using just `client.connect_async` instead of pure `client.connect` can solve this issue. `connect_async` is legal operation within `loop_start` and `loop_stop`.

Are there any possible issues with `connect_async`?

**Comment by j123b567** [comment]
May be related to #23

**Comment by jmrubillon** [comment]
would issuing the `client.connect_async()` before the `client.loop_start()` call be more accurate and in keeping with paho-mqtt examples?

**Comment by j123b567** [comment]
Unfortunately, there are no official examples using `connect_async()`.
Flask-Mqtt was using `connect_async` for a while but was removed by https://github.com/stlehmann/Flask-MQTT/commit/4cb671b503ceeb3beb165a2cc4ff91e886944416 without further details. 

It is little bit strange, because it works much better then with blocking `connect`.

**Comment by jmrubillon** [comment]
I've just submitted a pull request that fixes the connect to a connect_async call. Also changed the call order with loop_start coming after the connect_async call.
https://github.com/stlehmann/Flask-MQTT/pull/44#issue-233984545

**Comment by stlehmann** [comment]
I switched back to connect_async using the implementation of @jmrubillon. Thanks for this. I can't remember why I switched from connect_async to connect in the first place. Hope this works out well now :)
