### ISSUE TITLE
How to subscribe to multiple mqtt topics?

### ISSUE THREAD

**Issue by f4br1** [stlehmann/Flask-MQTT#35]
Hi, 

I am trying to use the Flask-MQTT and SocketIO to subscribe to multiple topics in the same broker? How can I do this? I am new to both extensions.

So far I am able to subscribe to a single topic and get the messages the broker sends, but I don't know how to do it for multiple topics.

Thanks!

**Comment by f4br1** [comment]
Hi, 

Thanks for you reply. The issue that I have is that each topic has a Token (used a password?). Therefore my question is, How can I subscribe to these topics given that each of them have a different Token? I addition to that, I need to handle the messages from each topic and display them on a webpage as soon as them get published. For this I am using Socket IO for the live updates without refreshing the page.  So far I am able to fo this for just one single topic, but I don't know how to do it for more than one. 

Is this the right way to do it? I am completely new to MQQT, Flask and Socket IO.

Thank you again!

**Comment by mntolia** [comment]
Hi f4br1,
There is no point in keeping a topic as a password. If i want to see all message published to a broker I can just subscribe to '#' which is a wildcard topic. Instead, you can use TLS for encryption .

If you are new to mqtt, I suggest you learn how it works completely. It can be learnt in a day.

Thank you
