### ISSUE TITLE
Is it possible to use flask_mqtt in dash module

### ISSUE THREAD

**Issue by muzmmilkhan** [stlehmann/Flask-MQTT#37]
Sir please tell me
Is it possible to use flask_mqtt module in dash module (web app)
Thanks in advance

**Comment by stlehmann** [comment]
Could you specify your question, please. Flask-MQTT is an add-on for the Flask microframework and thus can be used for web apps only. I don’t know about „Dash“ in this context. Maybe add a link or more context so it’s easier for me to understand your question. Regards

**Comment by muzmmilkhan** [comment]
Dash is Python framework for building web applications. It built on top of Flask, Plotly.js, React and React Js. It enables you to build dashboards using pure Python. Dash is open source, and its apps run on the web browser.
Here is the link:
https://dash.plot.ly/getting-started

I just want to use Mqtt in dash app please send the link or code to connect and subscribe if possible.
Or tell is it possible to use flask-mqtt in dash

**Comment by stlehmann** [comment]
I don’t know how well Flask addons are supported by Dash. However you can always use plain [paho-mqtt](https://github.com/eclipse/paho.mqtt.python) together with your Dash app.
