### ISSUE TITLE
Lose messages when subscribing

### ISSUE THREAD

**Issue by w52191** [stlehmann/Flask-MQTT#48]
Some messages are missing when subscribing to the server. I can guarantee that the server has received the published messages. But if 10 messages are published (interval > 1 second), sometimes I got 8 ones, some times I got 6, and sometimes 10... Anyone knows what's going on here? (All the settings are default)

**Comment by stlehmann** [comment]
Which [qos](https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/) are you using? If you use qos=0 it is common that some messages might get lost. If you want to make sure to receive all messages use qos=1 or qos=2 for both the publisher and the subscriber.

**Comment by w52191** [comment]
> Which [qos](https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/) are you using? If you use qos=0 it is common that some messages might get lost. If you want to make sure to receive all messages use qos=1 or qos=2 for both the publisher and the subscriber.

Yeah, I have tried that before. But it didn't help.
