### ISSUE TITLE
How to connect AWS  IoT

### ISSUE THREAD

**Issue by eric0324** [stlehmann/Flask-MQTT#49]
Hi , I create a Flask app...

I want to connect to AWS  IoT with `Flask-MQTT`

How to put my `ca`,`cert` and `key`...... and set config...

Please help me understand 

Thanks.

**Comment by stlehmann** [comment]
I have never used AWS so I'm sorry that I can not give you any hints on this.
However integrating TLS encryption in Flask-MQTT is possible by setting the approriate configuration keys. Have a look at the Flask-MQTT documentation: https://flask-mqtt.readthedocs.io/en/latest/configuration.html#configuration-keys.
