### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by lSh4dowl** [stlehmann/Flask-MQTT#50]
Can you please for the love of god add an option to disable logging ? My apache Error File is getting spammed with 
`[Thu Apr 11 19:57:20.009229 2019] [wsgi:error] [pid 4884:tid 1728836656] [2019-04-11 19:57:20,008] DEBUG in __init__: Subscribed to topic: home/entrance/door/auth, qos: 2`

**Comment by stlehmann** [comment]
This is adressed in PR #44.
