### ISSUE TITLE
some callbacks not triggering

### ISSUE THREAD

**Issue by philipobrien** [stlehmann/Flask-MQTT#51]
So in my app I have 

```
@mqtt.on_connect()
def handle_connect(client, userdata, flags, rc):
    logger.info("CLIENT CONNECTED")
```
which doesn't fire when a client connects.  More strangely, however, I have

```
@mqtt.on_subscribe()
def handle_subscribe(client, userdata, mid, granted_qos):
    logger.info("CLIENT SUBSCRIBED")
```

which fires if I put a `mqtt.subscribe("register", qos=2)` in the `handle_connect` callback, but if I subscribe from a client external to this app, e.g. MQTT.fx, it doesn't fire the callback, but the underlying library registers the subscription and logs it

```
mqtt_1           | 1557392697: New connection from 172.27.0.1 on port 1883.
mqtt_1           | 1557392697: New client connected from 172.27.0.1 as 9ed0f10ddb2d4ecca2b4da5e1c7cca4b (c1, k60).
```

If I publish a message from MQTT.fx the `handle_mqtt_message` callback works no problem.

**Comment by stlehmann** [comment]
Can this PR be closed?

**Comment by stlehmann** [comment]
Did you check if your mqtt messages have also been send with qos=2?
