### ISSUE TITLE
I don't understand how to pass the message.

### ISSUE THREAD

**Issue by badsmoke** [stlehmann/Flask-MQTT#52]
Hello, first thanks for this flask modul

I'm afraid I have an understanding problem.
How do I get the messages from the topics 

i would like to subscribe to several topics "hard" and print the values on my html page

later I want to input also publish

e.g. 

Topic "Sensor/Room1/Temperature1".
site http://localhost/mqtt

Can I please give someone an example of this?

**Comment by stlehmann** [comment]
Hello,

please have a look at the quick start guide and the sample application in the documentation.

Generally Github issues are not the right place to ask for help on a specific problem. You should use platforms like Stackoverflow for this or feel free to contact me directly. It is also good practice to add the source code that reflects your problem.

For now I will close this PR.

Regards
Stefan
