### ISSUE TITLE
I can't find any useful config MQTT_REFRESH_TIME in source code

### ISSUE THREAD

**Issue by b3g00d** [stlehmann/Flask-MQTT#53]
I looking to MQTT_REFRESH_TIME but I can't find it in the source code. Only on readme

**Comment by dinko-pehar** [comment]
Although it was added 2 years ago in `README.md`, my assumption it will be used for refreshing JWT token. Some example on [Google IoT  Core](https://cloud.google.com/iot/docs/how-tos/credentials/jwts#refreshing_jwts) platform . The maximum lifetime of a token is **24 hours + skew** (_10 mins_) , but in their examples on Python they refresh JWT after 20 minutes.
