### ISSUE TITLE
problem with sending MQTT PUBLISH when using multiprocessing

### ISSUE THREAD

**Issue by gromajus** [stlehmann/Flask-MQTT#57]
Hi!
In my code I am able to send Publish from the main thread, but when I use multiprocessing, the logger shows that the message was published, my the broker doesn't get any message.
The publish result code is zero.

Is it wanted behaviour? Or I am doing something wrong?

**Comment by stlehmann** [comment]
As written in the docs Flask-MQTT is not suitable for multiprocessing.
