### ISSUE TITLE
Publish returns MQTT_ERR_SUCCESS even though client is not connected

### ISSUE THREAD

**Issue by gusmb** [stlehmann/Flask-MQTT#61]
I tried publishing a message passing wrong credentials on config file. The publish method returned the tuple  result,mid=(0,1)
The message was not received on the broker and when I checked the method is_connected() on paho client it returned false. Despite that the result of the publish returned 0.

To verify this, I tried again with the right credentials, same publish result, but now the message was received and is_connected() returned True.

**Comment by stlehmann** [comment]
Could this be related to #43?

**Comment by stlehmann** [comment]
I'm closing this for now. If this is still an issue just leave a note.
