### ISSUE TITLE
Mqtt Client disconnects immediately after connect.

### ISSUE THREAD

**Issue by fuxey** [stlehmann/Flask-MQTT#64]
Hello, 
i tried the example project with my local mosquitto broker. But unfortunatly it worked not that good. subscription and publish are not forwared correctly. so i've added some logger messages:

```python
@mqtt.on_connect()
def handle_connect(client, userdata, flags, rc):
    print("CLIENT CONNECTED")

@mqtt.on_disconnect()
def handle_disconnect():
    print("CLIENT DISCONNECTED")


@mqtt.on_log()
def handle_logging(client, userdata, level, buf):
    print(level, buf)
```

16 Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k30) client_id=b'flask_mqtt'
CLIENT DISCONNECTED
16 Received CONNACK (0, 0)
CLIENT CONNECTED
16 Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k30) client_id=b'flask_mqtt'
CLIENT DISCONNECTED
16 Received CONNACK (0, 0)

The mosquitto Broker shows that it disconnects the flask app because of the client is already connected:

1580163250: New connection from 127.0.0.1 on port 1883.
1580163250: Client flask_mqtt already connected, closing old connection.
1580163250: New client connected from 127.0.0.1 as flask_mqtt (p2, c1, k30).
1580163250: No will message specified.
1580163250: Sending CONNACK to flask_mqtt (0, 0)
1580163251: New connection from 127.0.0.1 on port 1883.
1580163251: Client flask_mqtt already connected, closing old connection.
1580163251: New client connected from 127.0.0.1 as flask_mqtt (p2, c1, k30).
1580163251: No will message specified.
1580163251: Sending CONNACK to flask_mqtt (0, 0)
1580163251: Socket error on client flask_mqtt, disconnecting.

i also tested python.paho mqtt client without flask and it works correctly.

so any idea where's the problem? i also debugged the flask-mqtt code and cannot find issues.

**Comment by stlehmann** [comment]
Is this still an issue. If yes, please provide a minimal working example that describes your problem. I will close this issue for now as Github is not the best place to ask general questions about usage. Please try a forum like Stackoverflow first.

**Comment by kahlus2001** [comment]
How was this issue solved? I have the same problem.

**Comment by fuxey** [comment]
Hi,

Yes someone at stackoverflow helped me: see https://stackoverflow.com/questions/59951747/flask-mqtt-mqtt-client-disconnects-immediately-after-connect

**Comment by kahlus2001** [comment]
Thanks, this worked!
