### ISSUE TITLE
No connection to broker when 'generate_password_hash' from werkzeug.security is imported

### ISSUE THREAD

**Issue by WEB-FMA** [stlehmann/Flask-MQTT#66]
Hello!

I found the following bug while implementing an API that collects measurement data that my application consumes from an MQTT subscription.

Due to the API specification I have to use HTTP Basic Authentication, I'm currently using the Flask-HTTPAuth plugin for this purpose.
(https://github.com/miguelgrinberg/Flask-HTTPAuth)

The problem I found is that once I had the BasicAuth running, my MQTT values got no updates anymore. I tried to find the underlying issue, and discovered that the MQTT Plugin (Flask-MQTT)
doesn't connect to the broker at startup of the Flask-App anymore.

I tracked the problem back to the import of the 'generate_password_hash' function that gets imported from the werkzeug development webserver. Once this function gets called in the code
MQTT breaks.

Strangely engough I tried commenting out that import, and supplying my own mockup functions with the same function names. This seems to work without problems. I have the authentication as
well as correctly updated values from the MQTT subscription.

Thank you for writing such an nice Flask-Plugin in the first place, if I can help with finding the underlying problem and fixing the bug just contact me. I attached a working python code example that reproduces the problem as a .txt file
[2020-02-26_BUGREPORT_flask_mqtt.txt](https://github.com/stlehmann/Flask-MQTT/files/4255823/2020-02-26_BUGREPORT_flask_mqtt.txt)

**Comment by stlehmann** [comment]
> I tracked the problem back to the import of the 'generate_password_hash' function that gets imported from the werkzeug development webserver. Once this function gets called in the code
MQTT breaks.

Sorry for the late reply. Is this still an issue?

That is strange as this plugin does not use `generate_password_hash`. If Flask-MQTT stops working there should be a Traceback or an error message. Could you check for it and post it here?

**Comment by stlehmann** [comment]
I will close this for now. Feel free to comment if this is still an issue:

**Comment by stlehmann** [comment]
.
