### ISSUE TITLE
Losing db conext when I use create_app

### ISSUE THREAD

**Issue by zhazhalaila** [stlehmann/Flask-MQTT#68]
I use create_app function to create app in microapp.py.
```
from app import create_app, db, cli, socketio
from app.models import User, Sensor

app = create_app()

if __name__ == '__main__':
    socketio.run(app)
```
When I implement db insert operation in events blueprint. I get something wrong. Here is my code.
```
from app import socketio, mqtt, db
from app.events import bp
from flask_socketio import emit, send

@socketio.on('subscribe')
def handle_subcribe(data):
    mqtt.subscribe(str(data['topic']))
    print(mqtt.topics)
    print(db)

@socketio.on('unsubscribe')
def handle_unsubscribe(data):
    mqtt.unsubscribe(str(data['topic']))
    print(mqtt.topics)

@mqtt.on_message()
def handle_mqtt_message(client, userdata, message):
    print(db)
    data = dict(
        topic=message.topic,
        payload=message.payload.decode()
    )
    socketio.emit(message.topic, data=data)
```
When I `print(db)` in socketio, everything is ok.
```
<SQLAlchemy engine=mysql://root:***@127.0.0.1:3306/graduate?charset=utf8>
```
But when I `print(db)` in flask-mqtt, I get this
```
<SQLAlchemy engine=None>
```
Other operation like publish, subscribe.. etc are OK.

**Comment by zhazhalaila** [comment]
I had to try use app_context, but it's no use.
```
def create_app():
    .....
    db.init_app(app)
    .....
    with app.app_context():
        from app.events import bp as events_bp
        app.register_blueprint(events_bp)
        socketio.init_app(app)
        mqtt.init_app(app)
```

**Comment by zhazhalaila** [comment]
It seems like when I use `@mqtt.on_message()`, I'm out side of app context.
```
from flask import has_app_context

@mqtt.on_message()
def handle_mqtt_message(client, userdata, message):
    print(has_app_context())
```
Base this code, I get `False` not `True`.

**Comment by zhazhalaila** [comment]
Inspired by this [link](https://www.reddit.com/r/flask/comments/bizmlf/afusing_flasksqlalchemy_with_flaskmqtt_and_app/), I solve this problem by create a new app.
In `__init__.py`, for my new app I just want use db connect...
```
def create_mqtt_app(config_class=Config):
    app = Flask('mqtt_app')
    app.config.from_object(config_class)
    db.init_app(app)
    return app
```
And I use it like this.
```
from app import socketio, mqtt, db, create_mqtt_app

ctx = create_mqtt_app().app_context()

@mqtt.on_message()
def handle_mqtt_message(client, userdata, message):
    with ctx:
        print(db)
    data = dict(
        topic=message.topic,
        payload=message.payload.decode()
    )
    socketio.emit(message.topic, data=data)
```
I get right result. But I don't think this a good idea. Can anyone optimize it?

**Comment by stlehmann** [comment]
Use flask.current_app for pushing the app_context:

    from flask import current_app
    # ....
    @mqtt.on_message()
    def handle_mqtt_message(client, userdata, message):
         with current_app.app_context():
             # ....

**Comment by stlehmann** [comment]
See here:
* https://flask.palletsprojects.com/en/1.1.x/appcontext/
* https://flask.palletsprojects.com/en/1.1.x/api/#flask.current_app

**Comment by zhazhalaila** [comment]
Thanks. But when I use `current_app`, I can't get `current_app` in `@mqtt.on_message()`. But I can get `current_app` in `@socketio.on('subscribe')`. Here is my code.
```
@socketio.on('subscribe')
def handle_subcribe(data):
    print(current_app)

@mqtt.on_message()
def handle_mqtt_message(client, userdata, message):
    print(current_app)
```
When I print `current_app` in `@socketio.on('subscribe')`. I get this.
```
<Flask 'app'>
```
But when I print `current_app` in `@mqtt.on_message()`(I had to try send a mqtt message to activate it). I get nothing.

**Comment by stlehmann** [comment]
Ah you are right. Current_app can not be used. You might want to use your original Flask application object instead of creating a new one.

**Comment by zhazhalaila** [comment]
Thanks. I will create a new Flask application object.
