### ISSUE TITLE
MQTT_CLIENT_ID Not working

### ISSUE THREAD

**Issue by vusaalab** [stlehmann/Flask-MQTT#69]
Hi there!

The below code is not working. Tried to add clear_session too but not working

`app.config['MQTT_CLIENT_ID'] = 32324`

**Comment by stlehmann** [comment]
What is not working? Do you get an error? Please provide a Traceback if so.

**Comment by stlehmann** [comment]
I just checked the code. The client id is passed to the paho mqtt client. But it is supposed to be a string. I guess that might cause your error.
