### ISSUE TITLE
flask video server is very slow

### ISSUE THREAD

**Issue by mhechthz** [stlehmann/Flask-MQTT#72]
Hi,

I have following situation: I get jpegs via mqtt mosquitto with a frame rate of about 12 frames per second. I show these frames via `@app.route('/video_feed')` but get only one frame per second. What is wrong here?

```
#!/usr/bin/env python3
from flask import Flask, render_template, Response
from flask_mqtt import Mqtt
import datetime, time

#=====================================================================
# signal handling
import signal, sys, os

def handlerSIGINT(signum, frame):
    print('GOT SIGINT (%s) ... KILL process ...' % signum)
    os.kill(os.getpid(), signal.SIGTERM) #or signal.SIGKILL 

signal.signal(signal.SIGINT, handlerSIGINT)
#=====================================================================

app = Flask(__name__)

app.config['MQTT_BROKER_URL'] = 'the jpeg server'
app.config['MQTT_BROKER_PORT'] = 1883
app.config['MQTT_KEEPALIVE'] = 5
app.config['MQTT_USERNAME'] = 'myname'
app.config['MQTT_PASSWORD'] = 'mypass'
app.config['MQTT_REFRESH_TIME'] = 0.01
mqtt = Mqtt(app)

#=====================================================================

time0  = time.time()
frames = 0

@mqtt.on_connect()
def handle_connect(client, userdata, flags, rc):
    mqtt.subscribe('stream/camera')
    print("connected to topic ...")

@mqtt.on_message()
def handle_mqtt_message(client, userdata, message):
    global frame
    global time0
    global frames
    frame = message.payload[:]
    time.sleep(0.01)
    if time.time()-time0<1:
      frames += 1  
    else:
      print(frames,"frames per seconds ...",time0)
      frames = 0
      time0  = time.time()    

@mqtt.on_log()
def handle_logging(client, userdata, level, buf):
    # print("log:",level, buf)
    pass

@mqtt.on_disconnect()
def handle_disconnect():
    print("disconnected ...")

#=====================================================================

@app.route('/')
def index():
    return render_template('./index.html')

def gen():
    while True:

        global frame
    
        if frame == None: 
          print("frame is none ...")
          continue

        encodedImage = frame[:]

        time.sleep(0.01)

        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + encodedImage + b'\r\n')

@app.route('/video_feed')
def video_feed():
    return Response(gen(),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

#=====================================================================

if __name__ == '__main__':

    frame = None

    print("run flask app ...")
    app.run(host='0.0.0.0', debug=True, threaded=True, use_reloader=False)
    
```
The time.sleep() is the only way to see an image at all.

**Comment by stlehmann** [comment]
@mhechthz It's hard to tell where the bottleneck in your setup might be. Did you check if the MQTT server can handle your messages fast enough?

**Comment by mhechthz** [comment]
Meanwhile I changed the setup. Yes, mosquitto is fast enough to transfer about 14 frames per second. Now I write the frames with a pure python paho client to a memory disk based sqlite database and read with another pure flask application. The framerate is now about 11 fps per client, wich is ok for me. 

But this doesn't solve the original issue.

**Comment by stlehmann** [comment]
I'm not sure if mqtt is a good way to realise video streaming. After all it is a low-bandwith protocol for telemetry data. 

Have a look at this stackoverflow post: https://stackoverflow.com/questions/34031030/is-video-streaming-over-iot-protocols-feasible

Maybe you should think of using another protocol like websockets for this task.

**Comment by mhechthz** [comment]
Well, yes, it might not be a good idea but was more a test. Nevertheless I even don't get a few frames per second to work (paho-mqtt can transfer 14 fps) . So - beside that it is basically not the right approach - it seems to be too slow, so maybe buggy.

**Comment by stlehmann** [comment]
That is strange. Flask-MQTT is basically paho-mqtt with some convenience functions for Flask. Sure you used the same settings for both setups?
