### ISSUE TITLE
The disconnect method does not publish last_will_message

### ISSUE THREAD

**Issue by andrequeiroz2** [stlehmann/Flask-MQTT#83]
My question is if this behavior is correct, when the function below is called it disconnects from the broker,
but does not publish the will

```python
@mqtt.on_disconnect()
def handle_disconnect():
    mqtt._disconnect()
```

**Comment by stlehmann** [comment]
Flask-MQTT just calls the disconnect function of paho-mqtt. And in the documentation of paho-mqtt you will find this:

https://pypi.org/project/paho-mqtt/#disconnect

> disconnect()
> 
> Disconnect from the broker cleanly. Using disconnect() will not result in a will message being sent by the broker.
> 
> Disconnect will not wait for all queued message to be sent, to ensure all messages are delivered, wait_for_publish() from MQTTMessageInfo should be used. See publish() for details.

**Comment by stlehmann** [comment]
In fact the will message will only be sent if the client disconnects without calling disconnect():

https://pypi.org/project/paho-mqtt/#will-set

> Set a Will to be sent to the broker. If the client disconnects without calling disconnect(), the broker will publish the message on its behalf.
